name: Publish Docker image to Docker Hub

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version
        id: version
        run: |
          PKG_VERSION=$(jq -r .version package.json)
          echo "pkg_version=$PKG_VERSION" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            docker.io/${{ secrets.DOCKERHUB_REPO }}:${{ steps.version.outputs.pkg_version }}
            docker.io/${{ secrets.DOCKERHUB_REPO }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max


